import type { CollectionDefinition, Domain, Provider } from './model.js';

function definition(
  id: string, provider: Provider, domain: Domain, title: string,
  permissions: string[], reference: string, manual = false,
): CollectionDefinition {
  return { id, provider, domain, title, permissions, references: [reference], ...(manual ? { manual } : {}) };
}

const graph = (id: string, domain: Domain, title: string, permissions: string[], api: string): CollectionDefinition =>
  definition(id, 'graph', domain, title, permissions, `https://learn.microsoft.com/en-us/graph/api/${api}?view=graph-rest-1.0`);
const azure = (id: string, domain: Domain, title: string, reference: string): CollectionDefinition =>
  definition(id, 'azure', domain, title, ['Reader at each configured subscription; Security Reader for Defender for Cloud'], reference);
const github = (id: string, title: string, permissions: string[], path: string): CollectionDefinition =>
  definition(id, 'github', 'github', title, permissions, `https://docs.github.com/en/rest/${path}`);
const ado = (id: string, title: string, permissions: string[], path: string): CollectionDefinition =>
  definition(id, 'azureDevOps', 'azure-devops', title, permissions,
    `https://learn.microsoft.com/en-us/rest/api/azure/devops/${path}?view=azure-devops-rest-7.1`);
const manual = (id: string, provider: Provider, domain: Domain, title: string, reference: string): CollectionDefinition =>
  definition(id, provider, domain, title, ['Manual review with customer-approved least privilege; not requested by this collector'], reference, true);

/**
 * Permissions are prerequisites, not requests for consent. A completed collection
 * describes caller-visible, retention-limited API evidence, not guaranteed tenant-wide visibility.
 */
export const COLLECTION_CATALOG: CollectionDefinition[] = [
  graph('entra.organization', 'entra', 'Tenant identity read-back', ['Organization.Read.All'], 'organization-list'),
  graph('entra.users', 'entra', 'Users and available sign-in activity', ['User.Read.All', 'AuditLog.Read.All for signInActivity'], 'user-list'),
  graph('entra.groups', 'entra', 'Group security metadata', ['Group.Read.All'], 'group-list'),
  graph('entra.groupMemberships', 'entra', 'Direct group membership edges', ['GroupMember.Read.All', 'Directory.Read.All for member enrichment'], 'group-list-members'),
  graph('entra.applications', 'workload-identities', 'App registrations and credential metadata', ['Application.Read.All'], 'application-list'),
  graph('entra.servicePrincipals', 'workload-identities', 'Enterprise applications and managed identities', ['Application.Read.All'], 'serviceprincipal-list'),
  graph('entra.applicationOwners', 'workload-identities', 'Application owner relationships', ['Application.Read.All', 'User.Read.All for owner enrichment'], 'application-list-owners'),
  graph('entra.servicePrincipalOwners', 'workload-identities', 'Service principal owner relationships', ['Application.Read.All', 'User.Read.All for owner enrichment'], 'serviceprincipal-list-owners'),
  graph('entra.federatedCredentials', 'workload-identities', 'Application federated identity credential metadata', ['Application.Read.All'], 'application-list-federatedidentitycredentials'),
  graph('entra.appRoleAssignments', 'workload-identities', 'Service principal application permission grants', ['Application.Read.All'], 'serviceprincipal-list-approleassignments'),
  graph('entra.oauth2PermissionGrants', 'workload-identities', 'Delegated permission grants', ['Directory.Read.All'], 'oauth2permissiongrant-list'),
  graph('entra.directoryRoleDefinitions', 'entra', 'Directory role capability definitions', ['RoleManagement.Read.Directory'], 'rbacapplication-list-roledefinitions'),
  graph('entra.directoryRoleAssignments', 'entra', 'Directory role assignments', ['RoleManagement.Read.Directory'], 'rbacapplication-list-roleassignments'),
  graph('entra.directoryRoleAssignmentScheduleInstances', 'entra', 'Active directory role assignment schedule instances',
    ['RoleAssignmentSchedule.Read.Directory (or RoleManagement.Read.Directory)', 'Delegated: Global Reader or Security Reader (or another documented supported role)'],
    'rbacapplication-list-roleassignmentscheduleinstances'),
  graph('entra.directoryRoleEligibility', 'entra', 'Directory role eligibility schedule instances', ['RoleEligibilitySchedule.Read.Directory'], 'rbacapplication-list-roleeligibilityscheduleinstances'),
  graph('entra.authenticationRegistration', 'entra', 'Authentication registration capability report', ['AuditLog.Read.All'], 'authenticationmethodsroot-list-userregistrationdetails'),
  graph('entra.conditionalAccess', 'entra', 'Conditional Access policy metadata', ['Policy.Read.All'], 'conditionalaccessroot-list-policies'),
  graph('entra.riskyUsers', 'entra', 'Identity Protection risky users', ['IdentityRiskyUser.Read.All'], 'riskyuser-list'),
  graph('entra.riskySignIns', 'entra', 'Retained sign-ins with reported risk', ['AuditLog.Read.All'], 'signin-list'),
  graph('m365.secureScores', 'microsoft365', 'Microsoft Secure Score observations', ['SecurityEvents.Read.All'], 'security-list-securescores'),
  graph('m365.secureScoreControls', 'microsoft365', 'Microsoft Secure Score control profiles', ['SecurityEvents.Read.All'], 'security-list-securescorecontrolprofiles'),
  graph('m365.licenses', 'microsoft365', 'Subscribed product and service-plan metadata', ['LicenseAssignment.Read.All'], 'subscribedsku-list'),
  graph('m365.sharePointSettings', 'microsoft365', 'Tenant-level SharePoint sharing, authentication and idle-session metadata',
    ['SharePointTenantSettings.Read.All', 'Delegated: Global Reader or SharePoint Administrator'], 'sharepointsettings-get'),
  graph('intune.devices', 'intune', 'Managed device compliance and identity metadata', ['DeviceManagementManagedDevices.Read.All'], 'intune-devices-manageddevice-list'),
  graph('intune.compliancePolicies', 'intune', 'Device compliance policy inventory (not assignments)', ['DeviceManagementConfiguration.Read.All'], 'intune-deviceconfig-devicecompliancepolicy-list'),
  graph('intune.configurationPolicies', 'intune', 'Legacy device configuration inventory (not settings catalog)', ['DeviceManagementConfiguration.Read.All'], 'intune-deviceconfig-deviceconfiguration-list'),
  definition('defender.incidents', 'defender', 'defender-xdr', 'Caller-visible Defender XDR incident metadata',
    ['Incident.Read.All (application) or Incident.Read (delegated)'], 'https://learn.microsoft.com/en-us/defender-xdr/api-list-incidents'),
  definition('defender.alerts', 'defender', 'defender-xdr', 'Caller-visible Defender for Endpoint alert metadata',
    ['Alert.Read.All (application) or Alert.Read (delegated)'], 'https://learn.microsoft.com/en-us/defender-endpoint/api/get-alerts'),
  definition('defender.machines', 'defender', 'defender-xdr', 'Retained Defender for Endpoint machine metadata',
    ['Machine.Read.All (application) or Machine.Read (delegated)'], 'https://learn.microsoft.com/en-us/defender-endpoint/api/get-machines'),
  azure('azure.managementGroups', 'azure', 'Tenant-bound accessible management-group metadata',
    'https://learn.microsoft.com/en-us/rest/api/managementgroups/management-groups/list'),
  azure('azure.subscriptions', 'azure', 'Explicitly configured subscriptions and tenant evidence',
    'https://learn.microsoft.com/en-us/rest/api/resources/subscriptions/get'),
  azure('azure.resources', 'azure', 'Fixed Resource Graph security metadata projection',
    'https://learn.microsoft.com/en-us/rest/api/azureresourcegraph/resourcegraph/resources/resources'),
  definition('azure.policyCompliance', 'azure', 'azure', 'Caller-visible policy-state metadata for approved subscriptions',
    ['Reader at each configured subscription (Resource Graph policy-state visibility)'],
    'https://learn.microsoft.com/en-us/azure/governance/policy/samples/resource-graph-samples'),
  azure('azure.roleDefinitions', 'azure', 'Subscription-visible Azure RBAC definitions',
    'https://learn.microsoft.com/en-us/rest/api/authorization/role-definitions/list'),
  azure('azure.roleAssignments', 'azure', 'Subscription and descendant Azure RBAC assignments',
    'https://learn.microsoft.com/en-us/rest/api/authorization/role-assignments/list-for-scope'),
  azure('azure.federatedCredentials', 'workload-identities', 'User-assigned managed identity federation metadata',
    'https://learn.microsoft.com/en-us/rest/api/managedidentity/federated-identity-credentials/list'),
  azure('defenderCloud.pricings', 'defender-cloud', 'Defender for Cloud plan configuration metadata',
    'https://learn.microsoft.com/en-us/rest/api/defenderforcloud/pricings/list'),
  azure('defenderCloud.assessments', 'defender-cloud', 'Defender for Cloud assessment status metadata',
    'https://learn.microsoft.com/en-us/rest/api/defenderforcloud/assessments/list'),
  azure('defenderCloud.secureScores', 'defender-cloud', 'Defender for Cloud secure score metadata',
    'https://learn.microsoft.com/en-us/rest/api/defenderforcloud/secure-scores/list'),
  azure('defenderCloud.regulatoryCompliance', 'defender-cloud', 'Regulatory standard-level compliance summaries',
    'https://learn.microsoft.com/en-us/rest/api/defenderforcloud/regulatory-compliance-standards/list'),
  github('github.organizations', 'Organization security defaults', ['Organization metadata read; privileged settings may require organization administration read'], 'orgs/orgs#get-an-organization'),
  github('github.members', 'Organization membership with explicit member/admin role', ['Organization Members: read'], 'orgs/members#list-organization-members'),
  github('github.outsideCollaborators', 'Organization outside collaborators', ['Organization Members: read'], 'orgs/outside-collaborators#list-outside-collaborators-for-an-organization'),
  github('github.repositories', 'Organization repository visibility and security enablement metadata', ['Repository Metadata: read; Administration: read for security_and_analysis'], 'repos/repos#list-organization-repositories'),
  github('github.branchProtection', 'Default-branch protection metadata', ['Repository Administration: read'], 'branches/branch-protection#get-branch-protection'),
  github('github.rulesets', 'Repository and inherited ruleset metadata', ['Repository Metadata: read'], 'repos/rules#get-a-repository-ruleset'),
  github('github.workflowPermissions', 'Default workflow token permission settings', ['Repository Administration: read'], 'actions/permissions#get-default-workflow-permissions-for-a-repository'),
  github('github.workflows', 'Workflow inventory (no workflow source)', ['Repository Actions: read'], 'actions/workflows#list-repository-workflows'),
  github('github.runners', 'Repository-visible runner metadata', ['Repository Administration: read'], 'actions/self-hosted-runners#list-self-hosted-runners-for-a-repository'),
  github('github.environments', 'Environment protection metadata (no values)', ['Repository Actions: read'], 'deployments/environments#list-environments'),
  github('github.dependabotAlerts', 'Dependabot alert severity and package metadata', ['Repository Dependabot alerts: read'], 'dependabot/alerts#list-dependabot-alerts-for-a-repository'),
  github('github.codeScanningAlerts', 'Code scanning alert metadata (no source snippets)', ['Repository Code scanning alerts: read'], 'code-scanning/code-scanning#list-code-scanning-alerts-for-a-repository'),
  github('github.secretScanningAlerts', 'Secret scanning alert metadata with mandatory hide_secret=true', ['Repository Secret scanning alerts: read'], 'secret-scanning/secret-scanning?apiVersion=2026-03-10#list-secret-scanning-alerts-for-a-repository'),
  github('github.secretMetadata', 'Organization and repository Actions secret names only', ['Organization or Repository Secrets: read'], 'actions/secrets#list-repository-secrets'),
  ado('azureDevOps.projects', 'Caller-visible project visibility metadata', ['View project-level information'], 'core/projects/list'),
  ado('azureDevOps.repositories', 'Repository and default-branch metadata (no source)', ['Repository Read'], 'git/repositories/list'),
  ado('azureDevOps.branchPolicies', 'Branch policy configuration metadata', ['View project-level information; policy read access'], 'policy/configurations/list'),
  ado('azureDevOps.pipelines', 'Pipeline metadata inventory (no definitions or variables)', ['View builds'], 'pipelines/pipelines/list'),
  ado('azureDevOps.environments', 'Deployment environment inventory (not checks)', ['Environment Reader'], 'distributedtask/environments/list'),
  ado('azureDevOps.agentPools', 'Organization agent-pool metadata (no capabilities or credentials)', ['Agent pool Reader'], 'distributedtask/pools/get-agent-pools'),
  manual('m365.exchangeSettings', 'graph', 'microsoft365', 'Exchange Online configuration: manual specialist review',
    'https://learn.microsoft.com/en-us/exchange/exchange-online'),
  manual('m365.teamsSettings', 'graph', 'microsoft365', 'Teams security settings: manual specialist review',
    'https://learn.microsoft.com/en-us/microsoftteams/security-compliance-overview'),
  manual('intune.settingsCatalogPolicies', 'graph', 'intune', 'Settings catalog configuration and assignments: not implemented',
    'https://learn.microsoft.com/en-us/intune/intune-service/configuration/settings-catalog'),
  manual('intune.securityBaselines', 'graph', 'intune', 'Security baseline and endpoint-security assignment effectiveness: manual review',
    'https://learn.microsoft.com/en-us/intune/intune-service/protect/security-baselines'),
  manual('defender.office365Coverage', 'defender', 'defender-xdr', 'Defender for Office 365 configuration and coverage: manual review',
    'https://learn.microsoft.com/en-us/defender-office-365/mdo-about'),
  manual('defender.identityCoverage', 'defender', 'defender-xdr', 'Defender for Identity sensor coverage: manual review',
    'https://learn.microsoft.com/en-us/defender-for-identity/deploy/sensor-health-alerts'),
  manual('defender.cloudAppsCoverage', 'defender', 'defender-xdr', 'Defender for Cloud Apps configuration and integration coverage: manual review',
    'https://learn.microsoft.com/en-us/defender-cloud-apps/what-is-defender-for-cloud-apps'),
  manual('azure.managementGroupRoleAssignments', 'azure', 'azure', 'Management-group and tenant-root RBAC inheritance: manual review',
    'https://learn.microsoft.com/en-us/azure/role-based-access-control/scope-overview'),
  manual('defenderCloud.attackPaths', 'azure', 'defender-cloud', 'Defender for Cloud attack paths and DevOps integrations: manual review',
    'https://learn.microsoft.com/en-us/azure/defender-for-cloud/concept-attack-path'),
  manual('github.enterpriseSettings', 'github', 'github', 'Enterprise-wide settings and GHES: unsupported; GitHub.com organizations only',
    'https://docs.github.com/en/enterprise-cloud@latest/admin'),
  manual('github.workflowContent', 'github', 'code-to-cloud', 'Action pinning, CODEOWNERS and source/IaC review: no repository source is collected',
    'https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions'),
  manual('azureDevOps.serviceConnections', 'azureDevOps', 'azure-devops', 'Service connections: API may return authorization parameters; not fetched',
    'https://learn.microsoft.com/en-us/rest/api/azure/devops/serviceendpoint/endpoints/get-service-endpoints'),
  manual('azureDevOps.variableGroups', 'azureDevOps', 'azure-devops', 'Variable groups: API may return variable values; not fetched',
    'https://learn.microsoft.com/en-us/rest/api/azure/devops/distributedtask/variablegroups/get-variable-groups'),
  manual('azureDevOps.secureFiles', 'azureDevOps', 'azure-devops', 'Secure files and downloads: intentionally unavailable',
    'https://learn.microsoft.com/en-us/azure/devops/pipelines/library/secure-files'),
  manual('azureDevOps.environmentChecks', 'azureDevOps', 'azure-devops', 'Effective environment approvals/checks: manual review',
    'https://learn.microsoft.com/en-us/azure/devops/pipelines/process/approvals'),
  manual('azureDevOps.organizationPolicies', 'azureDevOps', 'azure-devops', 'Organization security policies, permissions and extensions: manual review',
    'https://learn.microsoft.com/en-us/azure/devops/organizations/security/about-security-identity'),
];
